secrets:
    datasource:
        url: "jdbc:mysql://localhost:3306/reelscout"
        username: "root"
        password: "root"

    jwt-secret-key: "e764f50181a05db5ef4bf802e432d5a123d4023b69794f5296bbf90f9b3ef89227e01cf029ccb6b7c95d7b0a93267c8b5bf6b7e33e70ec3142119aa36ca4b11d"

    s3:
        access-key: "Z6QGT71BS69KF9GKXNQR"
        secret-key: "NRiNCo5YoaYSc60UyEUMrfkH0VZawuIrcat0Zzde"
        endpoint: "http://localhost:9000"
        bucket: "reelscout-bucket"
        region: "us-east-1"

    elasticsearch:
        username: "elastic"
        password: "root"
        url: "http://localhost:9200"