# Spring Boot application configuration file
spring:
  config:
    import: classpath:application-secrets.yaml
  application:
    name: "backend"
  datasource:
    url: "${secrets.datasource.url}"
    username: "${secrets.datasource.username}"
    password: "${secrets.datasource.password}"
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT configuration
jwt:
  token:
    secret: "${secrets.jwt-secret-key}"
    expiration: 8640000  # 24 hours in milliseconds

# S3 configuration
s3:
  access-key: "${secrets.s3.access-key}"
  secret-key: "${secrets.s3.secret-key}"
  endpoint: "${secrets.s3.endpoint}"
  bucket: "${secrets.s3.bucket}"

# Api paths
api:
  basic-path: "/api/v1"
  paths:
    auth: "${api.basic-path}/auth"
    member: "${api.basic-path}/member"
    production: "${api.basic-path}/production"
    s3: "${api.basic-path}/s3"