spring:
  application:
    name: "backend"

  datasource:
    url: "jdbc:mysql://localhost:3306/reelscout"
    username: "root"
    password: "root"

  jpa:
    hibernate:
      ddl-auto: update

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration