# Spring Boot application configuration file
spring:
  config:
    import: classpath:application-secrets.yaml
  application:
    name: "backend"
  datasource:
    url: "${secrets.datasource.url}"
    username: "${secrets.datasource.username}"
    password: "${secrets.datasource.password}"
  jpa:
    hibernate:
      ddl-auto: create
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT configuration
jwt:
  token:
    secret: "${secrets.jwt-secret-key}"
    expiration: 30 # in minutes

# Api paths
api:
  basic-path: "/api/v1"
  paths:
    auth: "${api.basic-path}/auth"
    member: "${api.basic-path}/member"
    production: "${api.basic-path}/production"