# Spring Boot application configuration file
spring:
  config:
    import: classpath:application-secrets.yaml
  application:
    name: "backend"
  datasource:
    url: "${secrets.datasource.url}"
    username: "${secrets.datasource.username}"
    password: "${secrets.datasource.password}"
  jpa:
    hibernate:
      ddl-auto: update


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Api paths
api:
  basic-path: "/api/v1"
  paths:
    auth: "${api.basic-path}/auth"
    user: "${api.basic-path}/user"
    production: "${api.basic-path}/production"